USE SPRING;
CREATE TABLE IF NOT EXISTS TEAM(
	TEAM_ID MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS PLAYER(
	PLAYER_ID MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	TEAM_ID MEDIUMINT NOT NULL,
	FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

DELETE FROM TEAM;
LOAD DATA LOCAL INFILE 'team.csv' 
INTO TABLE TEAM 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';
QUIT